from pydantic import Field

from app.outputs.base_output import BaseOutput


class RAGAnswer(BaseOutput):
    """
    Structured response for Retrieval-Augmented Generation.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by the LLM.",
    )

    supporting_evidence: list[str] = Field(
        default_factory=list,
        description="Supporting evidence extracted from retrieved context.",
    )

    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Confidence score of the generated answer.",
    )